# Generated by Django 4.1 on 2025-05-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_options_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Галерея товаров'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Отзыв и оценку', 'verbose_name_plural': 'Отзывы и оценки'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Вариацию', 'verbose_name_plural': 'Вариации'},
        ),
    ]
