# Generated by Django 4.1 on 2025-05-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
