# Generated by Django 4.1 on 2025-05-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки'},
        ),
    ]
