# Generated by Django 5.2.1 on 2025-05-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updates',
            new_name='updated',
        ),
    ]
