# Generated by Django 5.2.1 on 2025-05-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_slag_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
