# Generated by Django 5.2.1 on 2025-06-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productfile_productlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='shop.product')),
            ],
            options={
                'verbose_name': 'Просмотр продукта',
                'verbose_name_plural': 'Просмотры продуктов',
                'unique_together': {('product', 'ip_address', 'viewed_at')},
            },
        ),
    ]
