# Generated by Django 4.1 on 2025-05-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплату', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
